DictEquipAdvance={}
DictEquipAdvance["1"]={id=1,equipTypeId=5,equipQualityId=4,starLevel=1,propAndAdd="3",contions="1_10000",description=""}
DictEquipAdvance["2"]={id=2,equipTypeId=5,equipQualityId=4,starLevel=2,propAndAdd="7",contions="1_30000",description=""}
DictEquipAdvance["3"]={id=3,equipTypeId=5,equipQualityId=4,starLevel=3,propAndAdd="10",contions="1_50000",description=""}
DictEquipAdvance["4"]={id=4,equipTypeId=5,equipQualityId=4,starLevel=4,propAndAdd="14",contions="2_100000",description=""}
DictEquipAdvance["5"]={id=5,equipTypeId=5,equipQualityId=4,starLevel=5,propAndAdd="17",contions="2_300000",description=""}
DictEquipAdvance["6"]={id=6,equipTypeId=1,equipQualityId=4,starLevel=1,propAndAdd="1",contions="1_10000",description=""}
DictEquipAdvance["7"]={id=7,equipTypeId=1,equipQualityId=4,starLevel=2,propAndAdd="3",contions="1_30000",description=""}
DictEquipAdvance["8"]={id=8,equipTypeId=1,equipQualityId=4,starLevel=3,propAndAdd="4",contions="1_50000",description=""}
DictEquipAdvance["9"]={id=9,equipTypeId=1,equipQualityId=4,starLevel=4,propAndAdd="5",contions="2_100000",description=""}
DictEquipAdvance["10"]={id=10,equipTypeId=1,equipQualityId=4,starLevel=5,propAndAdd="6",contions="2_300000",description=""}
DictEquipAdvance["11"]={id=11,equipTypeId=2,equipQualityId=4,starLevel=1,propAndAdd="1",contions="1_10000",description=""}
DictEquipAdvance["12"]={id=12,equipTypeId=2,equipQualityId=4,starLevel=2,propAndAdd="3",contions="1_30000",description=""}
DictEquipAdvance["13"]={id=13,equipTypeId=2,equipQualityId=4,starLevel=3,propAndAdd="4",contions="1_50000",description=""}
DictEquipAdvance["14"]={id=14,equipTypeId=2,equipQualityId=4,starLevel=4,propAndAdd="5",contions="2_100000",description=""}
DictEquipAdvance["15"]={id=15,equipTypeId=2,equipQualityId=4,starLevel=5,propAndAdd="6",contions="2_300000",description=""}
DictEquipAdvance["16"]={id=16,equipTypeId=3,equipQualityId=4,starLevel=1,propAndAdd="6",contions="1_10000",description=""}
DictEquipAdvance["17"]={id=17,equipTypeId=3,equipQualityId=4,starLevel=2,propAndAdd="13",contions="1_30000",description=""}
DictEquipAdvance["18"]={id=18,equipTypeId=3,equipQualityId=4,starLevel=3,propAndAdd="19",contions="1_50000",description=""}
DictEquipAdvance["19"]={id=19,equipTypeId=3,equipQualityId=4,starLevel=4,propAndAdd="25",contions="2_100000",description=""}
DictEquipAdvance["20"]={id=20,equipTypeId=3,equipQualityId=4,starLevel=5,propAndAdd="32",contions="2_300000",description=""}
DictEquipAdvance["21"]={id=21,equipTypeId=5,equipQualityId=3,starLevel=1,propAndAdd="2",contions="1_10000",description=""}
DictEquipAdvance["22"]={id=22,equipTypeId=5,equipQualityId=3,starLevel=2,propAndAdd="4",contions="1_30000",description=""}
DictEquipAdvance["23"]={id=23,equipTypeId=5,equipQualityId=3,starLevel=3,propAndAdd="6",contions="1_50000",description=""}
DictEquipAdvance["24"]={id=24,equipTypeId=1,equipQualityId=3,starLevel=1,propAndAdd="1",contions="1_10000",description=""}
DictEquipAdvance["25"]={id=25,equipTypeId=1,equipQualityId=3,starLevel=2,propAndAdd="1",contions="1_30000",description=""}
DictEquipAdvance["26"]={id=26,equipTypeId=1,equipQualityId=3,starLevel=3,propAndAdd="2",contions="1_50000",description=""}
DictEquipAdvance["27"]={id=27,equipTypeId=2,equipQualityId=3,starLevel=1,propAndAdd="1",contions="1_10000",description=""}
DictEquipAdvance["28"]={id=28,equipTypeId=2,equipQualityId=3,starLevel=2,propAndAdd="1",contions="1_30000",description=""}
DictEquipAdvance["29"]={id=29,equipTypeId=2,equipQualityId=3,starLevel=3,propAndAdd="2",contions="1_50000",description=""}
DictEquipAdvance["30"]={id=30,equipTypeId=3,equipQualityId=3,starLevel=1,propAndAdd="4",contions="1_10000",description=""}
DictEquipAdvance["31"]={id=31,equipTypeId=3,equipQualityId=3,starLevel=2,propAndAdd="8",contions="1_30000",description=""}
DictEquipAdvance["32"]={id=32,equipTypeId=3,equipQualityId=3,starLevel=3,propAndAdd="11",contions="1_50000",description=""}
DictEquipAdvance["33"]={id=33,equipTypeId=5,equipQualityId=5,starLevel=0,propAndAdd="18",contions="",description=""}
DictEquipAdvance["34"]={id=34,equipTypeId=5,equipQualityId=5,starLevel=1,propAndAdd="19",contions="",description=""}
DictEquipAdvance["35"]={id=35,equipTypeId=5,equipQualityId=5,starLevel=2,propAndAdd="20",contions="",description=""}
DictEquipAdvance["36"]={id=36,equipTypeId=5,equipQualityId=5,starLevel=3,propAndAdd="21",contions="",description=""}
DictEquipAdvance["37"]={id=37,equipTypeId=5,equipQualityId=5,starLevel=4,propAndAdd="22",contions="",description=""}
DictEquipAdvance["38"]={id=38,equipTypeId=5,equipQualityId=5,starLevel=5,propAndAdd="23",contions="",description=""}
DictEquipAdvance["39"]={id=39,equipTypeId=1,equipQualityId=5,starLevel=0,propAndAdd="7",contions="",description=""}
DictEquipAdvance["40"]={id=40,equipTypeId=1,equipQualityId=5,starLevel=1,propAndAdd="8",contions="",description=""}
DictEquipAdvance["41"]={id=41,equipTypeId=1,equipQualityId=5,starLevel=2,propAndAdd="9",contions="",description=""}
DictEquipAdvance["42"]={id=42,equipTypeId=1,equipQualityId=5,starLevel=3,propAndAdd="10",contions="",description=""}
DictEquipAdvance["43"]={id=43,equipTypeId=1,equipQualityId=5,starLevel=4,propAndAdd="11",contions="",description=""}
DictEquipAdvance["44"]={id=44,equipTypeId=1,equipQualityId=5,starLevel=5,propAndAdd="12",contions="",description=""}
DictEquipAdvance["45"]={id=45,equipTypeId=2,equipQualityId=5,starLevel=0,propAndAdd="7",contions="",description=""}
DictEquipAdvance["46"]={id=46,equipTypeId=2,equipQualityId=5,starLevel=1,propAndAdd="8",contions="",description=""}
DictEquipAdvance["47"]={id=47,equipTypeId=2,equipQualityId=5,starLevel=2,propAndAdd="9",contions="",description=""}
DictEquipAdvance["48"]={id=48,equipTypeId=2,equipQualityId=5,starLevel=3,propAndAdd="10",contions="",description=""}
DictEquipAdvance["49"]={id=49,equipTypeId=2,equipQualityId=5,starLevel=4,propAndAdd="11",contions="",description=""}
DictEquipAdvance["50"]={id=50,equipTypeId=2,equipQualityId=5,starLevel=5,propAndAdd="12",contions="",description=""}
DictEquipAdvance["51"]={id=51,equipTypeId=3,equipQualityId=5,starLevel=0,propAndAdd="34",contions="",description=""}
DictEquipAdvance["52"]={id=52,equipTypeId=3,equipQualityId=5,starLevel=1,propAndAdd="36",contions="",description=""}
DictEquipAdvance["53"]={id=53,equipTypeId=3,equipQualityId=5,starLevel=2,propAndAdd="38",contions="",description=""}
DictEquipAdvance["54"]={id=54,equipTypeId=3,equipQualityId=5,starLevel=3,propAndAdd="40",contions="",description=""}
DictEquipAdvance["55"]={id=55,equipTypeId=3,equipQualityId=5,starLevel=4,propAndAdd="42",contions="",description=""}
DictEquipAdvance["56"]={id=56,equipTypeId=3,equipQualityId=5,starLevel=5,propAndAdd="44",contions="",description=""}
