DictTryToPracticeType={}
DictTryToPracticeType["1"]={id=1,day=1,name="每日福利",rewards="6_86_1",count=12,num=0,sname="hotShopping1",description=""}
DictTryToPracticeType["2"]={id=2,day=1,name="副本任务",rewards="",count=0,num=0,sname="chapter",description=""}
DictTryToPracticeType["3"]={id=3,day=1,name="装备任务",rewards="",count=0,num=0,sname="equip",description=""}
DictTryToPracticeType["4"]={id=4,day=1,name="进阶任务",rewards="",count=0,num=0,sname="advance",description=""}
DictTryToPracticeType["5"]={id=5,day=2,name="每日福利",rewards="13_19_1",count=12,num=0,sname="hotShopping2",description=""}
DictTryToPracticeType["6"]={id=6,day=2,name="宝物任务",rewards="",count=0,num=0,sname="magic",description=""}
DictTryToPracticeType["7"]={id=7,day=2,name="试炼任务",rewards="",count=0,num=3,sname="fight1",description=""}
DictTryToPracticeType["8"]={id=8,day=2,name="境界任务",rewards="",count=0,num=0,sname="title",description=""}
DictTryToPracticeType["9"]={id=9,day=3,name="每日福利",rewards="7_88_1",count=14,num=0,sname="hotShopping3",description=""}
DictTryToPracticeType["10"]={id=10,day=3,name="命宫任务",rewards="",count=0,num=0,sname="constell",description=""}
DictTryToPracticeType["11"]={id=11,day=3,name="试炼任务",rewards="",count=0,num=3,sname="fight2",description=""}
DictTryToPracticeType["12"]={id=12,day=3,name="镶嵌任务",rewards="",count=0,num=0,sname="inlay",description=""}
DictTryToPracticeType["13"]={id=13,day=4,name="每日福利",rewards="7_95_1",count=13,num=0,sname="hotShopping4",description=""}
DictTryToPracticeType["14"]={id=14,day=4,name="缘分任务",rewards="",count=0,num=0,sname="luck",description=""}
DictTryToPracticeType["15"]={id=15,day=4,name="购物任务",rewards="",count=0,num=0,sname="hJYStore",description=""}
DictTryToPracticeType["16"]={id=16,day=4,name="试炼任务",rewards="",count=0,num=3,sname="fight3",description=""}
DictTryToPracticeType["17"]={id=17,day=5,name="每日福利",rewards="6_1_1",count=16,num=0,sname="hotShopping5",description=""}
DictTryToPracticeType["18"]={id=18,day=5,name="炼气任务",rewards="",count=0,num=0,sname="pagoda",description=""}
DictTryToPracticeType["19"]={id=19,day=5,name="进阶任务",rewards="",count=0,num=0,sname="equipAdvance",description=""}
DictTryToPracticeType["20"]={id=20,day=5,name="竞技任务",rewards="",count=0,num=0,sname="arena",description=""}
