package com.huayi.doupo.base.model.dict;

import java.util.HashMap;
import java.util.Map;

public class DictMapList {
	public static Map<Integer, Object> dictHoleConsumeMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictAdvanceMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictTitleDetailMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictAcupointNodeMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictKungFuTierAddMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictFireGainMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictThingMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictPagodaDropMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictRecruitCardMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictBarrierDropMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictBarrierMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictBarrierLevelMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictChapterMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictLootChipMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictChipMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictPillMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictRestoreMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictMagicLevelMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictAchievementMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictGenerBoxThingMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictSpecialBoxThingMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictCardMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictEquipmentMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictMagicMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictBarrierDropTypeMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictRecruitSpecialCardMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictRecruitTimesGetMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictActivitySignInMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictActivityGrabTheHourMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictActivityPrivateSaleMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictActivityDailyDealsMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictActivityMonthCardStoreMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictEquipAdvanceMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictFightSoulMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictFightSoulUpgradeExpMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictFightSoulUpgradePropMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictMineBoxThingMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictWingAdvanceMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictWingStrengthenMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictHoldStarGradeRewardMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictEquipAdvanceredMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictMagicrefiningMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictCardLuckMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictEquipSuitReferMap = new HashMap<Integer, Object>();
	public static Map<Integer, Object> dictWingLuckMap = new HashMap<Integer, Object>();
}